secretNamePrefix: remote-secret-
targetNamespaces: [default]

eksClusters:
  - assumeRoleARN: arn:aws:iam::123456789012:role/eks-admin
    clusters: [hoge]

execTemplate:
  apiVersion: client.authentication.k8s.io/v1beta1
  args: [token, -i, "{{ .clusterName }}"]
  env:
    - name: AWS_DEFAULT_REGION
      value: ap-northeast-1
    - name: AWS_STS_REGIONAL_ENDPOINTS
      value: regional
